language: generic

dist: xenial
os: linux

cache:
  - directories:
      - "$HOME/emacs/"        # Stable Emacs binaries.
      - "$HOME/.config/emacs" # Packages.

env:
  jobs:
    # - EMACS_VERSION=26
    - EMACS_VERSION=27
    - EMACS_VERSION=master

before_install:
  - curl -LO "https://github.com/npostavs/emacs-travis/releases/download/bins/emacs-bin-$EMACS_VERSION.tar.gz"
  - tar -xaf "emacs-bin-$EMACS_VERSION.tar.gz" -C /
  - export PATH="/tmp/emacs/bin:${PATH}"
  - emacs --version

install:
  # There is no option to skip confirmation in <= Emacs 27 so override y-or-n-p.
  - emacs --batch -l ./init.el --eval "(progn (package-refresh-contents) (defun y-or-n-p (_) t) (package-install-selected-packages))"

script:
  - mkdir -p ~/.config/emacs && mkdir -p ~/ops/emacs/{.git,config} && mkdir -p ~/ops/.git
  - emacs --batch -l ./init.el --eval "(progn (package-initialize))" -f ec-test

notifications:
  email:
    on_success: never
    on_failure: always
